### ISSUE TITLE
Structure du repo

### ISSUE THREAD

**Issue by zckrs** [eleven-labs/presentations-ateliers#1]
Super idée le repo pour regrouper les présentations.

Il pourrait être intéressant d'organiser le repo avec une arborescence de dossier basé sur les auteurs ou/et technos.
De plus on pourrait créer une page github (gh-pages) pour visualiser directement les présentations sur http://eleven-labs.github.io/presentations-ateliers

**Comment by lepiaf** [comment]
je pense qu'on peut le laisser simple. certains sujet peuvent avoir plusieurs thèmes.

**Comment by lepiaf** [comment]
L'idée du gh-pages est bien

**Comment by baruica** [comment]
On pourrait laisser l'arbo comme ça, mais arranger la page github différemment?

**Comment by lepiaf** [comment]
j'ai activé la page http://eleven-labs.github.io/presentations-ateliers
